### ISSUE TITLE
Anyone can call claimModelRevenue

### ISSUE THREAD

**Issue by JasonFengGit** [ora-io/OAO#5]
```
// any can call this function
    function claimModelRevenue(uint256 modelId) external ifModelExists(modelId) {
        ModelData storage model = models[modelId];
        require(model.accumulateRevenue > 0, "accumulate revenue is 0");
        uint256 transferRevenue = model.accumulateRevenue;
        model.accumulateRevenue = 0;
        (bool success, ) = (model.receiver).call{value: transferRevenue}("");
        require(success, "claimModelRevenue transfer failed");
    }
```

Hi, can anyone explain to me why anyone can call this function? seems vulnerable to me. Thanks!

**Comment by 0x1cc** [comment]
The function `claimModelRevenue` can be invoked by anyone. Note that the revenue from the model is not distributed to the entity who calls the function (i.e., `msg.sender`). Instead, it’s allocated to `model.receiver`. Therefore, it doesn’t present a vulnerability as the funds are not directed to an arbitrary caller.
